export const WORKOUT_CONSTANTS = {
  WEIGHT_STEP_KG: 2.5,
  DEFAULT_REST_SECONDS: 90,
  DEFAULT_SETS: 3,
  DEFAULT_REPS_MIN: 8,
  DEFAULT_REPS_MAX: 12,
  DEFAULT_STARTING_WEIGHT_KG: 60,
  PRESCRIBED_SETS_FALLBACK: 3,
} as const;
